//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento
    {
        public int id { get; set; }
        public int idPagamento { get; set; }
        public int idSubServico { get; set; }
        public int idGrupo { get; set; }
        public string marca { get; set; }
        public string matricula { get; set; }
        public string tipoPagamento { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        public virtual Grupos Grupos { get; set; }
        public virtual Pagamentos Pagamentos { get; set; }
        public virtual SubServicos SubServicos { get; set; }
    }
}
