//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string NIF { get; set; }
        public string sexo { get; set; }
        public string contacto { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dataN { get; set; }
        public Nullable<System.DateTime> data_criacao { get; set; }
    }
}
