//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresas()
        {
            this.FaturasEmpresa = new HashSet<FaturasEmpresa>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string NIF { get; set; }
        public string localizacao { get; set; }
        public string descricao { get; set; }
        public string contacto { get; set; }
        public string email { get; set; }
        public string banco { get; set; }
        public string num_conta { get; set; }
        public string IBAN { get; set; }
        public Nullable<System.DateTime> data_criacao { get; set; }
        public Nullable<System.DateTime> data_modificacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaturasEmpresa> FaturasEmpresa { get; set; }
    }
}
