//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionarios()
        {
            this.FuncGroup = new HashSet<FuncGroup>();
            this.Pagamentos = new HashSet<Pagamentos>();
            this.Caixa = new HashSet<Caixa>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string username { get; set; }
        public Nullable<System.DateTime> dataN { get; set; }
        public string sexo { get; set; }
        public string senha { get; set; }
        public string acesso { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> data_criacao { get; set; }
        public Nullable<System.DateTime> data_modificacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FuncGroup> FuncGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagamentos> Pagamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Caixa> Caixa { get; set; }
    }
}
