//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagamentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pagamentos()
        {
            this.Atendimento = new HashSet<Atendimento>();
        }
    
        public int id { get; set; }
        public string cliente { get; set; }
        public System.TimeSpan horaEntrada { get; set; }
        public System.DateTime dataEntrada { get; set; }
        public Nullable<decimal> montante { get; set; }
        public Nullable<decimal> multicaixa { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> total { get; set; }
        public int idFuncionario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atendimento> Atendimento { get; set; }
        public virtual Funcionarios Funcionarios { get; set; }
    }
}
