//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promocoes
    {
        public int id { get; set; }
        public string matricula { get; set; }
        public Nullable<int> contagem { get; set; }
        public Nullable<int> total { get; set; }
    }
}
