//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAtendimentos
    {
        public int id { get; set; }
        public string cliente { get; set; }
        public string serviço { get; set; }
        public string modelo { get; set; }
        public string grupo { get; set; }
        public string marca { get; set; }
        public string matricula { get; set; }
        public string pagamento { get; set; }
        public Nullable<decimal> valor { get; set; }
        public System.TimeSpan hora { get; set; }
        public System.DateTime data { get; set; }
        public string estado { get; set; }
        public string funcionário { get; set; }
    }
}
