//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCaixa
    {
        public int id { get; set; }
        public Nullable<decimal> montante { get; set; }
        public Nullable<decimal> multicaixa { get; set; }
        public Nullable<decimal> total { get; set; }
        public string referência { get; set; }
        public System.DateTime data { get; set; }
        public string funcionário { get; set; }
    }
}
