//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicesCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwFacturasEmpresas
    {
        public int id { get; set; }
        public int idEmpresa { get; set; }
        public string nome { get; set; }
        public Nullable<int> numEncomenda { get; set; }
        public string tipo { get; set; }
        public Nullable<int> kilos { get; set; }
        public Nullable<decimal> precoKilo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> data_criacao { get; set; }
    }
}
